language: node

node:
  - 6.2

sudo: required

env:
  global:
  - PGPORT=5432
  - PGHOST=localhost

services:
  - postgresql
  - redis

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart
  - psql --version
  - psql -U postgres -c 'create database "khan";'
  - psql -U postgres khan -c 'create extension "uuid-ossp";'
  - psql -U postgres -c 'CREATE ROLE travis LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE;'
  - psql -U postgres -c 'GRANT ALL ON SCHEMA public TO travis;'

before_install:
  - nvm install 6.2.2
  - nvm use 6.2.2

install:
  - make setup-ci

script:
  - node --version
  - make test-ci
