language: node

node:
  - 6.2

sudo: required

services:
  - postgresql
  - redis

addons:
  postgresql: "9.4"

before_install:
  - nvm install 6.2.2
  - nvm use 6.2.2

install:
  - make setup

script:
  - node --version
  - make test
